[package]
name = "herald_common"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast   = "1.2"

[dependencies.rusqlite]
version = "0.20.0"
optional = true

[dependencies.kson]
path = "../kson"

[dependencies.kcl]
path = "../kcl"

[features]
rusqlite_ = ["rusqlite"]
