[package]
name = "platform_dirs"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"

[dependencies.once_cell]
version = "1.2.0"

[features]
default = []
deploy_desktop = []
