[package]
name = "messages_helper"
version = "0.1.0"
authors = ["Baeo Maltinsky <baeo.maltinsky@gmail.com>"]
edition = "2018"

[dependencies]
im = "14.0.0"
unicode-segmentation = "1.6.0"
json = "0.12.0"
lru = "0.4.1"
once_cell = "1.2.0"
parking_lot = "0.10.0"

[dependencies.herald_common]
path    = "../../herald_common"

[dependencies.heraldcore]
path    = "../../heraldcore"

[dependencies.search_pattern]
path    = "../../heraldcore/search_pattern"

[dev-dependencies.coremacros]
path = "../../heraldcore/coremacros"
