[package]
name = "server_errors"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_cbor      = "0.10"
serde           = { version = "1.0",            features = ["derive"] }
herald_common = { path = "../../herald_common" }
tokio-postgres  = "0.5.0-alpha.1"
tokio           = "0.2.0-alpha.6"

[dependencies.warp]
git = "https://github.com/seanmonstar/warp"
rev = "5c26956"
