[package]
name = "herald"
version = "0.1.0"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>", "mobile-bungalow <pwmay@ucsc.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
crossbeam-channel = "0.3.9"
dashmap           = "1.0.5"
im-rc             = "13.0.0"
lazy_static       = "1.4.0"
libc              = "0.2.60"
parking_lot       = "0.9.0"
serde             = "1.0.99"
serde_cbor        = "0.10.1"


[dependencies.herald_common]
path    = "../herald_common"

[dependencies.heraldcore]
path    = "../heraldcore"


[target.'cfg( all( target_family = "unix", not( any( target_os = "android", target_os="ios" ) ) ) )'.dependencies.notify-rust]
version = "3.6.2"

[dev-dependencies]
serial_test        = "0.2.0"
serial_test_derive = "0.2.0"

[profile.release]
panic = "abort"

[features]
deploy_desktop = ["heraldcore/deploy_desktop"]
